
****************************************************************

应用版本：  5.1.12.63002
记录时间：  2019-05-10 10:47:32,690 
线程ID  ：  [1] 
日志级别：  ERROR 
出错类  ：  LastMessageLog property:[(null)] - 
错误描述：  Error TryGetResource Error:C:\Users\user\AppData\Roaming\Seewo\EasiNote5\Dependencies\ClassicalWorks_Metadata

****************************************************************

应用版本：  5.1.12.63002
记录时间：  2019-05-10 17:31:08,012 
线程ID  ：  [72] 
日志级别：  ERROR 
出错类  ：  LastMessageLog property:[(null)] - 
错误描述：  Error [TimeCapsule][DeviceInfo] 结束录播驱动失败，录播驱动不存在：

****************************************************************

应用版本：  5.1.12.63002
记录时间：  2019-05-10 17:31:08,162 
线程ID  ：  [23] 
日志级别：  ERROR 
出错类  ：  LastMessageLog property:[(null)] - 
错误描述：  Error {"Header":{"Type":0,"Id":"SetClientinfoForce","SourceId":"17800","TargetId":"Server","SerialNumber":""},"Content":"{\"Item1\":\"2b420975-52b1-4ae4-a8d1-e5037748174d\",\"Item2\":\"\"}"}
System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Cvte.IPC.Network.IDuplexService.SendMessage(String message)
   在 Cvte.IPC.Framework.ClientService.<SendInner>b__13_0(Message m)
